### PR TITLE
added Sync Match Rate and Poll Success Rate panels

### PR DESCRIPTION
**Pull request by antmendoza**
## What was changed

- Added Sync Match Rate and Poll Success Rate panels. We usually refer to these metrics went we talk with users/customers about their workers' setup. 
- fix duplicated panel ids

## Checklist

1. Closes 

2. How was this tested:

3. Any docs updates needed?

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by TimSimmons** [comment]
could you throw a screenshot of what these graphs look like in here?

**Comment by antmendoza** [comment]
@TimSimmons 


Screenshot 2023-02-08 at 23 46 27
Screenshot 2023-02-08 at 23 46 09
Screenshot 2023-02-08 at 23 45 53

**Comment by antmendoza** [comment]
@TimSimmons 

Screenshot 2023-02-08 at 23 55 45
Screenshot 2023-02-08 at 23 55 23
Screenshot 2023-02-08 at 23 54 58

**Comment by TimSimmons** [comment]
Screen Shot 2023-02-09 at 08 57 41

for the percentage ones, id recommend changing the unit to `Percentage (0-1.0)` so people can see the percentage sync match rate as a percentage rather than 0-1, which can be confusing, otherwise 👍

**Comment by antmendoza** [comment]
Done @TimSimmons 

image

**Review by TimSimmons — APPROVED** [review]

**Pull request merged**
